package de.spreclib.java.enums.longtermstorage;

public enum LongTermStorageContainer {
  PP_TUBE_ZEROFIVE_TO_TWO_ML,
  CRYOTUBE_ONE_TO_TWO_ML,
  PLASTIC_CRYOSTRAW,
  STRAW,
  PP_TUBE_GREATER_FIVE_ML,
  MICROPLATE,
  PARAFFIN_BLOCK,
  BAG,
  DRY_TECHNOLOGY_MEDIUM,
  PP_TUBE_FOURTY_TO_FIFEHUNDRED_MICROL,
  ORIGINAL_PRIMARY_CONTAINER;
}
