package de.spreclib.java.enums;

public enum SprecPartType {
	FLUID_SAMPLE_TYPE,
	PRIMARY_CONTAINER,
	PRE_CENTRIFUGATION,
	FIRST_CENTRIFUGATION,
	SECOND_CENTRIFUGATION,
	POST_CENTRIFUGATION,
	SOLID_SAMPLE_TYPE,
	TYPE_OF_COLLECTION,
	WARM_ISCHEMIA_TIME,
	COLD_ISCHEMIA_TIME,
	FIXATION,
	FIXATION_TIME,
	LONG_TERM_STORAGE
}
